### ISSUE TITLE
[Feature request] Possibility to configure a cronjob/schedule for the workflow

### ISSUE THREAD

**Issue by ldeluigi** [djspiewak/sbt-github-actions#27]
Right now the plugin doesn't offer an option to rerun the workflow with a cron-job [schedule](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule). It would be a nice new feature, as it happens that builds get stale with time.

**Comment by djspiewak** [comment]
I'm *tempted* to say that this is just out of scope. Builds can only get stale if they aren't reproducible, which would seem to be the root of the problem there. Is there something I'm missing? What's the use-case here?

**Comment by ldeluigi** [comment]
If a project depends on some online resource (a web API, for example), that can change or become unavailable, it can happen that it breaks without the developer knowing it.

**Comment by tusharmath** [comment]
This would be great because one could do something like — 

```yml
name: Scala Steward
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.SCALA_STEWARD_PAT }}
```
