### ISSUE TITLE
Question: How to pass parameters with `with` keyword?

### ISSUE THREAD

**Issue by ItoYo16u** [djspiewak/sbt-github-actions#43]
How can I configure `with` option in `sbt-github-action`  `WorkflowStep.Use`  when github actions yaml like below is needed?
```yaml
- name: Do Something
        uses: foo/bar@v1
        with:
          param1: ${{ secrets.param1}}
          param2: ${{secrets.param2}}
```
